//This module performs the automatic construction of the Swagger documentation.
//The module can identify the endpoints and automatically capture methods such as to get, post, put, and so on.
const swaggerAutogen = require('swagger-autogen')();

//An object containing the details of the documentation. 
//If not informed, or if any parameter of the object is omitted, the default values ​​will be used.
const doc = {
  info: {
    title: 'Contacts API',
    version: '0.0.1',
    description: 'REST CONTACTS API (WDD341)'
  },
  host: 'smoothiexpress-api.onrender.com',
  schemes: ['https']
};

//It will be the file generated by the module containing the documentation in the format identified by Swagger.
const outputFile = './swagger.json';
//Files containing the endpoints or routes. These are the files that contain methods such as get, post, put, use, and so on
const endpointsFiles = ['./routes/index.js'];

// Building documentation without starting the project
swaggerAutogen(outputFile, endpointsFiles, doc);

// Building documentation without starting the project and run the server after
// swaggerAutogen(outputFile, endpointsFiles, doc).then(async () => {
//   await import('./server.js');
// });